# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField()),
                ('light_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MoistureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField()),
                ('moisture_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField()),
                ('temperature_value', models.CharField(max_length=50)),
            ],
        ),
    ]
