# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_info', '0002_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='CalendarNote',
        ),
        migrations.RenameModel(
            old_name='TemperatureSensor',
            new_name='Sensor',
        ),
        migrations.DeleteModel(
            name='LightSensor',
        ),
        migrations.DeleteModel(
            name='MoistureSensor',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='temperature_value',
            new_name='sensor_value',
        ),
    ]
